name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -  uses: actions/checkout@v2
      -  uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_repo_url: "Foxy/foxy-elements"
          npm_build_command: "npm run prepack"
      - name: Run NPM install & Prepack
        run: |
          cd ..
          ls
      - name: Checkout Foxy/foxy-elements
        uses: actions/checkout@v2
        with:
          repository: Foxy/foxy-elements
          path: foxy-elements
      - name: ls elements
        run: ls
      # - name: Checkout Foxy/foxy-elements
      #   uses: actions/checkout@v2
      #   with:
      #     repository: Foxy/foxy-elements
      #     path: foxy-elements

      # - uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      #   run: - run: aws s3 sync ./dist s3://[bucket-name]

      # - name: Run NPM install & Prepack
      #   run: ls
