name: Test

on:
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_repo_url: "Foxy/foxy-elements"
          npm_build_command: "npm run prepack"
      - name: Checkout Foxy/foxy-elements
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.github_repo_url  }}
          path: foxy-elements

      - name: Run NPM install & Prepack
        run: ls
